# -*- coding: utf-8 -*-
"""Yolo object detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kv0wwq13Hlj3AG4wGRxrPhQM6ITVmcBj
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/yolo_custom_Model_Training/

#!unzip /content/drive/MyDrive/yolo_custom_Model_Training/custom_data.zip -d /content/drive/MyDrive/yolo_custom_Model_Training/

!git clone https://github.com/AlexeyAB/darknet /content/drive/MyDrive/yolo_custom_Model_Training/darknet

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolo_custom_Model_Training/darknet

ls

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolo_custom_Model_Training/

!python custom_data/creating-files-data-and-name.py

!python custom_data/creating-train-and-test-txt-files.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolo_custom_Model_Training/custom_weight/

!wget https://pjreddie.com/media/files/darknet53.conv.74

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolo_custom_Model_Training

!darknet/darknet

!darknet/darknet detector train custom_data/labelled_data.data darknet/cfg/yolov3_custom.cfg custom_weight/darknet53.conv.74 -dont_show

